### ISSUE TITLE
REPORTE DE PRACTICA_CONTROL

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Rigoberto2001#2]
[REPORTEPRACTICA_CONTROLPERSONALIZADO_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Rigoberto2001/files/6339205/REPORTEPRACTICA_CONTROLPERSONALIZADO_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by garaudy12** [comment]
Calificación: 19 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
